### PR TITLE
Upgrade Jest from v17 to v19

### PR DESCRIPTION
**Pull request by iamlacroix**
Upgrades Jest from v17 to v19. Updates the Jest config to account for a breaking change.

### CODE REVIEW

**Comment by sloanelybutsurely** [comment]
@iamlacroix Is this included in the current set of pending upstream changes?

**Comment by iamlacroix** [comment]
@zperrault Hmm, it looks like v18 is.

**Comment by sloanelybutsurely** [comment]
@iamlacroix We can close this out right? We'll get `jest@^20` with the next upstream release also.

**Comment by iamlacroix** [comment]
This was upgraded via upstream changes in our v9 release.

**Pull request closed without merging**
