### PR TITLE
Use upstream eslint config

### PR DESCRIPTION
**Pull request by sloanelybutsurely**
`eslint-config-react-app` is arguably better than our config and doesn't have formatting conflicts with prettier.

This would be a MAJOR version bump as this could "break" builds in the linting step. Additionally, flow would have to be run as a separate step (something that some folks have been asking for as well)

### CODE REVIEW

**Comment by jblock** [comment]
I'd be all for this, though tepid if there's an immense number of breakages as a result of enabling it. By any chance, have we tried running this branch against any of our apps to see if that's the case?

**Comment by sloanelybutsurely** [comment]
@jblock I have run it in `onboarding_app`. There were two things that were new errors (using `location` without `window.`) that were easy to correct.

It also caught some a11y issues that were easy to correct.

However, switching to `flow` proper is likely to be a much bigger deal. It seems that the `flowtype-errors` eslint plugin we were using before was hiding a lot of flow errors from us and things have ballooned a bit out of control (particularly in `@trunkclub/web`).

If you'd like to try this out, I've published a version under the `beta` tag so run `yarn add -D @trunkclub/build@beta` in your app to see what's changed.

**Comment by jblock** [comment]
Interesting...we could probably exclude `@trunkclub/web` in individual flowconfigs if that's the primary source of `flow` errors (since I would imagine that we wouldn't want to put too much effort into it at this point anyways)

**Comment by sloanelybutsurely** [comment]
[Output from `account_app`, `onboarding_app`, `trunk_app`, `stylist_app`, and `member_profile_app`](https://gist.github.com/zperrault/e92e67162a07498d119ee516fc85d5c5)

**Comment by jblock** [comment]
@zperrault Interesting! Thankfully, the PropTypes one is [easily codemod-able](https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types)

**Comment by eanplatter** [comment]
Is there a reason prettier wouldn't fix any breaking issues this causes?

**Pull request merged**
