### PR TITLE
Service manager compatibility

### PR DESCRIPTION
**Pull request by sloanelybutsurely**
@trunkclub/ui 

This makes some changes to the webpack dev config to make integration with service manager easier. It also creates a fork of the `react-dev-utils` script so it connects to the dev server running on localhost instead of trying to connect to it through trunkclub.dev.

I have also disabled the dependency bundling for now. A future PR will fix that issue. Some things can't be bundled due to postinstall issues with compiled deps (node-sass, leveldown). If you have ideas about how to fix/detect that, I'm all ears 👂 

Thanks!

### CODE REVIEW

**Comment by jblock** [comment]
Does it have to be all-or-nothing with the bundled dependencies? Can we exclude the ones that have issues and have those get natively rebuilt on installation? 

EDIT: In particular, it sounds like they already do this for `fsevents`?

**Comment by sloanelybutsurely** [comment]
@jblock Doesn't have to be all-or-nothing. Right now I'm mostly trying to figure out which ones are the problem... Testing is a slow process 😞

**Comment by kellyrmilligan** [comment]
i'm a bit confused. do we have a fork of react-dev-utils? if so, where is it?

**Comment by sloanelybutsurely** [comment]
@kellyrmilligan https://github.com/trunkclub/create-react-app/tree/master/packages/react-dev-utils

**Comment by kellyrmilligan** [comment]
oh, I expected it to be a fork on it's own and not inside this repo. I see
now that it's just published separately but is in that repo. gotcha.
lerna....

**Pull request merged**
