### PR TITLE
More SVG options

### PR DESCRIPTION
**Pull request by sloanelybutsurely**
I'd like to have a good solution for SVG icons without much configuration but SVGs are a bit tricky.

There are a couple of places we could use SVGs and we probably want them to work a bit differently.

1. Use in `url()`s in SCSS
   - We'd probably want `file-loader` here. So that the `url()` ends up pointing to the right file in the production build
2. Usage in our React components
   - I'm thinking of using the `svg-sprite-loader` with a special component that will create a sprite sheet of the svgs (example below)

```js
import React from 'react'
import classnames from 'classnames'

const Svg = ({filename, className, ...props}) => (
  <svg
    {...props}
    className={classnames('Svg-Icon', className)}
    dangerouslySetInnerHTML={{
      __html: `<use xlink:href="${require('!!svg-sprite!svgo!assets/${filename}.svg')}"></use>`
    }}
  />
)

export default Svg

// Usage

<Svg filename="monogram" />
```

(the `!!` in the `require` call disable all loaders established in the webpack config to allow bypassing the `file-loader` that's probably be turned on for all svgs by default.)

Now that I'm writing this out, the `svg-sprite-loader` and associated component could be their own module and people could install it if they needed it. The question then is how to get a separate file in production.

Very open to ways to do this. I'd _really really really_ like to avoid adding an additional step outside of the webpack config.

@trunkclub/ui

### CODE REVIEW

**Comment by kellyrmilligan** [comment]
In exploring these options I'd like to keep an eye towards server compatibility. 

is there a way for loaders to be used and still be ok on the server?

**Comment by sloanelybutsurely** [comment]
@kellyrmilligan Yes, using webpack to create the server build.

**Comment by kellyrmilligan** [comment]
That has been a non starter in the past, so I would rather not depend on that being the answer.

**Comment by jblock** [comment]
I'm not opposed to webpack-for-the-server-build. I think we did it wrong
with CMApp (particularly, working it around a messy and non server friendly
flux framework) and there's likely been a lot more momentum on different
ways to attack the problems we had. Not saying it's the cleanest answer,
but it could be _an_ answer 😅

**Comment by jblock** [comment]
Sorry, I didn't respond to the initial implementation at all and GAHH I
JUST MISSED MY TRAIN STOP NOOOOOOOO

OK I'll take a gander later

**Comment by kellyrmilligan** [comment]
@jblock we can explore it again, and I don't want to use cm app as our only example. I tried it, dan tried it, and both times we ran into issues. I have found its best to let node be node and webpack be webpack.

**Comment by sloanelybutsurely** [comment]
@kellyrmilligan @jblock If you don't mind, I'd rather we discuss how we should handle SVG loading and save the server side rendering for another time. I don't think that we should avoid using webpack loaders for the sake of potential server-side support. My goal is to have all of the features that `@trunkclub/build@4.0.0` had and server-side rendering support wasn't one of them. That being said, I do think that if we do server-side rendering, running both client and server builds through webpack will have the lowest barrier to entry and thus get the most support and then adoption.

As far as SVGs go, the https://github.com/kisenka/svg-sprite-loader is working rather nicely for using SVGs from react components (using the reference component I included in my initial post) but currently has issues when being used with the ExtractTextPlugin.

Ideally we'd want the spritesheet to be a separate file in production to reduce the size of our initial JS bundle (although we can get similar perf using code-splitting).

Another option would be to use something like the `raw-loader` to pull in the SVG source itself and use `dangerourlySetInnerHTML` to inject the entire svg source into the page.

I'd really like to get the `svg-sprite-loader` working and I'm happy to take a look at https://github.com/kisenka/svg-sprite-loader/issues/66.

What are your thoughts on these options? Do you have other ideas?

**Comment by jblock** [comment]
👍 Good point--we'll just want to make sure that we're not explicitly designing _against_ SSR as a pattern, but I have very high confidence that most webpack-loader strategies won't do that (so long as the assets can be extracted out during the build, and more desirably, we can intelligently include those extracted assets without userland configuration). 

I like the semantics of the `svg-sprite-loader` (and subsequently, think that the remaining issue is with the ExtractTextPlugin is probably pretty straightforward to fix)--my main concern is with having inline loader syntax. Do you think it's fair to have this build pipeline enforce a naming scheme for these icons as to prescribe their path through this loader? `*-sprite.svg` or something? 

My other major concern is having the SVG (or any asset references, for that matter) be analyzable during build-time--e.g, if I create an `Icon` component with a `filename="krull"`, then I'd expect that Webpack throws an error that it can't find the file with the name of "krull" and output that to the console. Does this do that?

**Comment by sloanelybutsurely** [comment]
@jblock 🤔  An enforced naming scheme would also enforce where things could be used. If you're using an svg in your CSS, you'd have to duplicate it with another name to use it in your JS somewhere else. Still an option though. 

We can get build time analysis of svg imports if we don't use expressions from the require statements. We can do that by moving the `require` out of the `<Svg />` component and using it when passing in props (in most cases) but then we either have to enforce naming or have a bunch of requires with loader syntax. I'm cool with loader syntax in one place and in module code, but not thrilled about telling people to use it. I don't want people to have to know what webpack is doing and I think that breaks that rule.

**EDIT:** Some things we _could_ do... Write our own loader for svgs that uses the appropriate loader based on the other loaders being used (is `css-loader` or `style-loader` being used? proxy to `file-loader`, otherwise, use the `svg-sprite-loader` kind of stuff). I think that's what we'd want and I'd argue it is just about as :sparkles: magic ✨  as telling people to use a different filename... WDYT?

**EDIT2:** It might also be possible to get the `svg-sprite-loader` working in CSS `url()` as well. Investigating.

**Comment by kellyrmilligan** [comment]
>  If you don't mind, I'd rather we discuss how we should handle SVG loading and save the server side rendering for another time. I don't think that we should avoid using webpack loaders for the sake of potential server-side support. My goal is to have all of the features that @trunkclub/build@4.0.0 had and server-side rendering support wasn't one of them. 

@jblock 
@zperrault I think you hit the nail on the head. 4.0 has no concept of this, and for the time being neither should 5.0 if it's goal is feature parity.  I'm bringing out the consensus card on this one. This should be discussed at the summit with the group, and until then we favor the status quo, which at the moment is up to the the team that is responsible for the particular app. 

As for server side rendering being potential, it is not. Until the business tells us we do not need cm_app to be searchable by google, server rendering is a real thing for us to contend with. We know that if we use regular javascript and do not have loader syntax that it will work. We do not know enough at this time if using webpack to build the server bundle will work fully with combinations of  loaders, etc. By that measure alone, we should not have loader syntax in files. 

so what I propose is to drop this issue entirely for now until we get more apps on this system, and can reach consensus on if we need a built in approach for icons.

**Comment by sloanelybutsurely** [comment]
@kellyrmilligan 

> 4.0 has no concept of this, and for the time being neither should 5.0 if it's goal is feature parity.

This is untrue. [`build@4.0.0` uses `file-loader` to load SVGs](https://github.com/trunkclub/tcweb-build/blob/master/src/webpack/tc-web-config.js#L184-L188). I'll keep it that way and bring this up at the next UI summit.

**Comment by kellyrmilligan** [comment]
@zperrault good point, forgot the file loader was in there. sounds good.

**Pull request closed without merging**
