### PR TITLE
Upstream merges

### PR DESCRIPTION
**Pull request by sloanelybutsurely**
This hasn't been tested at all yet... still a WIP

### CODE REVIEW

**Comment by iamlacroix** [comment]
Should we first be merging from a stable release instead of master?

**Comment by sloanelybutsurely** [comment]
.....

**Comment by sloanelybutsurely** [comment]
> I tried so hard 
> And got so far 
> But in the end 
> It doesn't even matter 
  
  [_linkin park_](https://www.youtube.com/watch?v=GL0CqVbhs7Q)

**Comment by iamlacroix** [comment]
I mean, is create-react-app master working for others? They haven't released anything with webpack v2 yet.

**Comment by sloanelybutsurely** [comment]
@iamlacroix Nah I think you're right

**Comment by sloanelybutsurely** [comment]
Closing this. Just opened a PR against `0.9.x` upstream branch over here: #83

**Pull request closed without merging**
