### PR TITLE
Enable eslint `fix` option and write fixes to disk

### PR DESCRIPTION
**Pull request by sloanelybutsurely**
@trunkclub/ui Should this be opt-in? opt-out?

### CODE REVIEW

**Review by eanplatter — APPROVED** [review]
DOIT

**Comment by kellyrmilligan** [comment]
Agreed. We were already operating with it fixing things for us so we should keep that

**Comment by sloanelybutsurely** [comment]
@eanplatter @kellyrmilligan Neither of you answered my question 😄

**Comment by kellyrmilligan** [comment]
it should not be opt-in or opt-out. it should just be 🚀

**Pull request merged**
